### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by SourcingDenis** [gfrancqu/linkedin2GoPhish#1]
Hello @gfrancqu! Super curious to see how it works and get used to it. Could you please briefly walk me through the usage process? Many thanks for your time in advance! 🙌 
Cheers,
Denis

**Comment by gfrancqu** [comment]
Hi, I just added some sample usage of the script and an virtualenv  based installation process. Feel free to ask if you face issues understanding or running the script

**Comment by Space-Cased** [comment]
I had almost a verbatim message from SourcingDenis on my github account. IHe is asking us all a simple question, something along the lines on if we can explain how it works. . I am just not quite sure if he is legitimately concerned with the answer.  My question, is there anything he has to gain in our answer besides its content?
